FROM jenkins/jenkins:2.440.3-lts

USER jenkins
RUN jenkins-plugin-cli --plugins blueocean:1.25.5 build-timestamp:1.0.3 timestamper:1.17 pollscm:1.3.1

USER root

# Configs de ambiente
ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"
ENV ACCESS_KEY ${ACCESS_KEY}
ENV SECRET_KEY ${SECRET_KEY}

# Instala Python + pip + venv
RUN apt update && \
    apt install -y python3 python3-pip python3-venv

# Cria venv no container
RUN python3 -m venv /opt/venv

# Copia o requirements.txt do host para o container
COPY ./requirements.txt /tmp/requirements.txt

# Instala os pacotes dentro do venv
RUN /opt/venv/bin/pip install --upgrade pip && \
    /opt/venv/bin/pip install -r /tmp/requirements.txt

# Torna o venv default no PATH
ENV PATH="/opt/venv/bin:$PATH"

# Copia os scripts de configuração do Jenkins
COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy
